feat: Add Raycaster class and example
wafflestudio/interactive-study pull request #21
Opened 2024-06-26 09:50 UTC by nuagenic

WIP

2024-06-28 06:40 UTC, minkyu97 requested changes
고생했어~~

> 1. 엄밀히 말하면 main.ts에서 정의하는 함수가 이벤트리스너의 콜백 함수가 아닌데, EventCallback이라는 이름을 쓰고 있어서 요 부분이 좀 걸리는데... 좋은 네이밍 있으면 추천 부탁드립니다

`이벤트리스너의 콜백 함수가 아닌데` 이 부분이 잘 이해가 안 가는데, 일단 해당 타입을 export 하고있지 않고 내부에서만 사용하니 괜찮지 않을까요?? dom 명세에서 사용하는 이름이랑 겹치는 것도 아니니 굳이 고칠 필요까진 없다고 봅니다.

> 2. 그리고 drag 동작의 경우, 저희가 조작하는 게 DOM element는 아니기 때문에 drag event를 직접 쓸 수는 없다고 생각했고, mousemove, mouseup, mousedown을 이용하여 구현했는데요. 이 과정에서 offset이나 dragging과 같은 프로퍼티를 들고 있는 것도 지저분하고, 복수의 이벤트를 동시에 써야 된다는 점이 좀 신경쓰였습니다... 그래서 클래스에 그냥 심을까 생각했는데, 그럼 drag를 커스터마이징할 때 기존의 intersects만 받는 식으로 처리하기도 어려울 것 같아 통일성을 해치는 거 같기도 하여... 일단 지저분하게 두었는데 좋은 방법 있을까요??

사실 DOM 에서의 drag 이벤트 또한 우리가 상상하는 엘리먼트를 자유자재로 드래그해서 움직이는 게 아니라 해당 엘리먼트를 캡처해서 반투명 이미지를 만들고, 그 이미지가 우리 마우스를 따라다니는 방식이잖아요? 요러한 방식의 drag 이벤트는 굳이 구현할 필요가 없을 것 같구요, 만든다해도 DOM의 drag event 는 threejs Object 대상으로 발동하는 게 아니라 canvas 를 대상으로 발동할테니 크게 의미가 없어보입니다. 그냥 지금처럼 mouse 관련 이벤트 몇 개만 지원해주고, 사용하는 사람들이 drag 에 대한 처리를 하는 게 맞다고 보여요.
대신.. 사용하는 사람이 drag 에 대한 처리를 하려면 현재 마우스 위치를 알아야할 것 같은데, this.mouseCoords 를 callback 에 인자로 넣어주면 좋겠습니다. 꼭 drag가 아니더라도 Mouse 가 현재 canvas 의 어디에 위치해있는지 알면 상당히 유용할 것 같아요.

2024-06-28 06:40 UTC, minkyu97 commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +export class Raycaster extends THREE.Raycaster {
P3) Raycaster 이름이 THREE.Raycaster 와 중복되는 게 걸리는데, 다른 좋은 네이밍 없을까요?

2024-06-28 06:40 UTC, minkyu97 commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +    return this.intersectObjects(this.scene.children);
P2) Scene 내부 모든 children 에 대해 검사하는 게 괜찮을까요?? 성능 문제는 차치하더라도 무의미하게 너무 많은 intersect 들이 반환되어서 콜백 내부에서 해당 intersect 들을 다시 순회하며 원하는 Mesh Object 가 존재하는지 찾아야하는 부분이 불편할 것 같아요.
차라리 registerCallback 시점에 targetObjects 들을 등록해서 각 콜백마다 검사를 하는 건 어떨까요? 기존보다 `intersectObjects` 호출 횟수는 증가하겠지만 검사 대상이 되는 객체들이 많이 줄어들테니 너무 많은 콜백을 등록하지 않는 한 성능 이슈는 오히려 줄어들 것 같고, 동일한 targetObjects 들에 여러 콜백이 등록되면 해당 배열을 캐싱해서 성능을 최적화시키는 것도 어렵지 않아보입니다

2024-06-28 06:40 UTC, minkyu97 commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +  }
P1) 요거 제대로 작동하나요??
`this.handleEvent` 가 동일한 `EventType` 에 대해서 동일한 함수를 반환하도록 캐싱을 하거나, 아니면 생성 시점에 `EventType` 별로 함수를 만들어서 멤버 변수로 가지고 있어야할 것 같습니다.

그리고 들고있는 callback 들도 초기화시켜주는 게 좋겠습니다.

2024-06-28 06:40 UTC, minkyu97 commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +    this.mouseCoords.y = -(event.clientY / window.innerHeight) * 2 + 1;
P1) 현지네처럼 `canvas 크기 !== window 크기` 인 경우 정상적으로 작동하지 않을 수 있습니다. 그런 케이스들을 대응하려면 뷰포트의 꼭짓점 좌표들을 받아서 사용해야될 거예요.

2024-06-28 06:40 UTC, minkyu97 commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +  offset: THREE.Vector3 = new THREE.Vector3();
얘네는 당장은 안 쓰는 건가요? 아니면 사용자가 가져다 마음대로 쓰면 되는 건가요?

2024-06-28 06:40 UTC, minkyu97 commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +  offset: THREE.Vector3 = new THREE.Vector3();
P2) 그리고 나머지 프로퍼티들도 사용자들이 직접 사용할 필요가 없다면 private으로 감춰주는 게 좋아보입니다! getIntersects 같은 메서드도 포함해서요.

2024-06-28 06:40 UTC, minkyu97 commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +    this.callbacks[eventType]!.push(callback);
EventType 이 5개 밖에 안되는데 생성자 시점에 미리 배열은 초기화해두고 null check 는 안 하는 게 어떨까요?

2024-07-01 09:02 UTC, yeolyi commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +}
이벤트 타입별 콜백을 모아놓는게 목적이라면 `Map` 자료구조가 나을 것 같아요.   아래 코드를 보니 `keyof EventCallbacks`으로 간접적으로 이벤트 타입을 표현하던데 이를 별도의 타입으로 정의하고 `Map`을 사용하면 보다 깔끔해질 것 같아요. 예시:  

```ts 
type EventType = 'mousemove' | 'click' | 'mousedown' // ... 
type EventCallbackMap = Map<EventType, EventCallbackMap[]> 
```

2024-07-01 09:02 UTC, yeolyi commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +export class Raycaster extends THREE.Raycaster {
콜백 등록하는게 핵심이면 `ListenableRaycaster`....?

2024-07-01 09:02 UTC, yeolyi commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +  handleEvent(eventType: keyof EventCallbacks) {
이벤트의 처리가 여기서 일어나는게 아니라 이벤트를 처리해주는 함수를 반환하니 `handleEvent`보다는 `createEventHandler` 등등의 이름이 좋을 것 같아요.

2024-07-01 09:02 UTC, yeolyi commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +    return this.intersectObjects(this.scene.children);
> 차라리 registerCallback 시점에 targetObjects 들을 등록해서 각 콜백마다 검사를 하는 건 어떨까요?

저도 이 방법이 좋다고 생각해요

2024-07-01 09:02 UTC, yeolyi commented on projects/find-waffle/src/example/raycaster/main.ts
> +    if (raycaster.selectedObject !== intersectedObject) {
콜백 내부에서 바깥 스코프에 있는 `raycaster`에 접근하도록 하는 것보다 (`Array.prototype.map`의 콜백처럼) 함수 인자로 콜백이 등록된 `raycaster` 객체를 전달해주는게 사용성이 좋을 것 같아요. 

이러면 정의 시점에 `raycaster`에 대한 참조를 가질 수 없는 유틸성 콜백등을 만드는 상황등에서 편리할 것 같습니다.

2024-07-01 09:02 UTC, yeolyi commented on projects/find-waffle/src/example/raycaster/main.ts
> +    raycaster.selectedObject = intersects[0].object;
이런식으로 `Raycaster` 사용자가 공통적으로 해야되는 처리는 `RayCaster` 객체 내부에서 하는게 좋을 것 같아요.

2024-07-10 18:39 UTC, nuagenic commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +export class Raycaster extends THREE.Raycaster {
좋아요! 수정했습니다

2024-07-10 18:40 UTC, nuagenic commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +    return this.intersectObjects(this.scene.children);
`targetObjects`를 `registerCallback` 시점에 넘겨주는 방식으로 변경했습니다!

2024-07-10 18:42 UTC, nuagenic commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +  }
`eventListeners`라는 private property 안에서 이벤트 리스너를 등록하고 제거하는 방식으로 변경했습니다! 그런데 이렇게 될 시에 constructor가 너무 뚱뚱해지는 거 같은데.... 이건 괜찮나요??

2024-07-10 18:42 UTC, nuagenic commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +    this.mouseCoords.y = -(event.clientY / window.innerHeight) * 2 + 1;
넵 수정했습니다!!

2024-07-10 18:46 UTC, nuagenic commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +  offset: THREE.Vector3 = new THREE.Vector3();
`dragging`과 `offset`의 경우는 드래그를 구현하기 위해 클래스에 선언해 놓았던 건데요, (모든 이벤트에서 범용적으로 쓰이는 프로퍼티가 아니니) 사용자가 외부에서 선언하여 쓰는 것이 나을 것 같아 없앴습니다. `selectedObject`는 모든 이벤트에서 사용될 것 같아 `getIntersects`에 로직을 추가해 두었습니다!

2024-07-10 18:46 UTC, nuagenic commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +    this.callbacks[eventType]!.push(callback);
좋아요 수정했습니다!

2024-07-10 18:46 UTC, nuagenic commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +}
저도 이게 더 깔끔할 거 같아서 수정했습니다! 감사합니다:)

2024-07-10 18:47 UTC, nuagenic commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +  handleEvent(eventType: keyof EventCallbacks) {
좋아요 수정했습니다!

2024-07-10 18:50 UTC, nuagenic commented on projects/find-waffle/src/example/raycaster/main.ts
> +    raycaster.selectedObject = intersects[0].object;
`selectedObject`의 경우 raycaster 내부로 로직 옮겨두었습니다! dragging과 관련된 것은 아예 객체 외부에서 사용자가 제어하는 것이 나을 것 같아 제외시켰습니다

2024-07-10 18:56 UTC, nuagenic commented
달아주신 코멘트 반영하여 수정했습니다! mouseCoords의 경우 모든 콜백함수가 필요할 것 같지는 않아(drag도 기본 동작을 위해서는 `mouseCoords` 대신 `intersect.point`를 사용하는 것이 더 간단하게 해결될 것으로 보이기도 하고요), 우선은 선택적 매개변수로 처리해 두었습니다. 혹시 보시고 더 수정할 사항이 있으면 코멘트 달아주세요! 이제 진짜 빨리빨리 작업하겠습니다ㅠㅡㅠ

2024-07-13 14:49 UTC, minkyu97 commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +  }
요정도야 뭐.. 전 이런 거 보기 불편하면 private 메소드로 빼는 스타일이긴한데, 취향껏 하면 될 것 같습니다.

2024-07-13 14:51 UTC, minkyu97 approved these changes
리뷰가 늦었네요 ㅎ
수고하셨습니다

2024-07-13 14:51 UTC, minkyu97 commented on projects/find-waffle/src/libs/raycaster/Raycaster.ts
> +    const rect = canvas.getBoundingClientRect();
이런 방법도 있었군요 👍

2024-07-18 10:50 UTC, merged